version: 2
updates:
- package-ecosystem: "gradle"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "10:00"
    timezone: "UTC"
  labels:
    - "test-dependencies"
  allow:
    - dependency-type: "all"
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]

