version: 2
updates:
- package-ecosystem: "gradle"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "10:00"
    timezone: "UTC"
  labels:
    - "test-dependencies"
  allow:
    - dependency-type: "all"
  ignore:
    # Pin Spring Boot version to 3.0.1
    - dependency-name: "org.springframework.boot"
      versions: [">3.0.1"]
    # Pin Spring Dependency Management version to 1.1.6
    - dependency-name: "io.spring.dependency-management"
      versions: [">1.1.6"]
    # Keep existing rule to ignore major version updates
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]

